import { describe, expect, it } from "vitest";
import { Assistant } from "../src/moteur/assistant";
import { REGLAGES } from "../src/savoir/coordonnees";
import { BASE } from "../src/savoir/index";

const assistant = new Assistant(BASE, REGLAGES);

const QUESTIONS: Array<[rang: number, question: string]> = [
  [85, "Quel extracteur de jus choisir ?"],
  [86, "La cire remplace-t-elle le bouchon ou la capsule ?"],
  [87, "Quelle différence entre broyeur, presse et extracteur ?"],
  [88, "Comment retrouver la bonne pièce de rechange pour mon appareil ?"],
  [89, "Qu’est-ce qu’une mère de vinaigre et est-elle obligatoire ?"],
  [90, "Comment ouvrir une bouteille cirée sans faire d’éclats ?"],
  [91, "Comment éviter la moisissure sur une confiture ?"],
  [92, "Un produit convient-il au contact alimentaire ?"],
  [93, "Comment sécher les bouteilles sans les recontaminer ?"],
  [94, "Quel vin utiliser pour faire du vinaigre ?"],
  [95, "Peut-on appliquer de la cire sur une capsule ou un bouchon synthétique ?"],
  [96, "Combien de temps conserver une confiture maison ?"],
  [97, "Comment choisir entre deux références proches ?"],
  [98, "Combien de temps avant la mise peut-on laver les bouteilles ?"],
  [99, "Peut-on faire du vinaigre avec du cidre ?"],
  [100, "Comment éviter les bulles, coulures ou fissures dans la cire ?"],
  [101, "Quelle différence entre une boucheuse à mors et une boucheuse à levier ?"],
  [102, "Comment nettoyer un tuyau de soutirage à l’intérieur ?"],
  [103, "Comment choisir un casier selon le nombre et le format des bouteilles ?"],
  [104, "Pourquoi mon vinaigre ne démarre-t-il pas ?"],
  [105, "Quel chauffe-cire choisir pour une petite ou grande série ?"],
  [106, "Une boucheuse peut-elle poser des capsules couronne et des bouchons liège ?"],
  [107, "Quelle différence entre soutirage, transvasement et mise en bouteille ?"],
  [108, "Comment nettoyer une dame-jeanne à col étroit ?"],
  [109, "Peut-on stocker des bouteilles de champagne dans un casier à vin ?"],
  [110, "Pourquoi une pellicule se forme-t-elle à la surface ?"],
  [111, "Comment entretenir les mors d’une boucheuse ?"],
  [112, "À quelle température mettre le vin en bouteille ?"],
  [113, "Peut-on utiliser de l’eau de Javel pour les bouteilles ?"],
  [114, "Comment éviter la moisissure sur les étiquettes ?"],
  [115, "Peut-on faire du cidre avec des pommes de table ?"],
  [116, "Comment nettoyer le robinet en bois d’un vinaigrier ?"],
  [117, "Faut-il fixer la boucheuse sur un établi ?"],
  [118, "Comment choisir entre siphon, pompe et remplisseuse ?"],
  [119, "Comment retirer les anciennes étiquettes et la colle ?"],
  [120, "Que faire si la cave est trop sèche ?"],
  [121, "Quand récolter les pommes à cidre ?"],
  [122, "Comment installer la bonde et le robinet sans les casser ?"],
  [123, "Peut-on boucher des demi-bouteilles avec la même boucheuse ?"],
  [124, "Comment arrêter automatiquement le remplissage au bon niveau ?"],
  [125, "Que faire si la cave est trop humide ?"],
  [126, "Combien de temps peut-on garder les pommes avant pressage ?"],
  [127, "Faut-il remplir les bocaux à chaud ou à froid ?"],
  [128, "Comment éviter de casser une bouteille pendant le bouchage ?"],
  [129, "Peut-on remplir des bouteilles encore humides ?"],
  [130, "Quand faut-il carafer ou décanter un vin ?"],
  [131, "Comment nettoyer un broyeur et un pressoir après usage ?"],
  [132, "Quel espace de tête laisser dans un bocal ?"],
  [133, "Quelle cadence peut-on atteindre avec une boucheuse manuelle ?"],
  [134, "Comment limiter les pertes au fond d’une cuve ?"],
  [135, "Comment servir un vieux vin sans remettre le dépôt en suspension ?"],
  [136, "Pourquoi mon cidre reste-t-il plat ?"],
  [137, "Pourquoi du liquide sort-il des bocaux pendant le traitement ?"],
  [138, "Le bouchon en liège doit-il être traité ou préparé avant utilisation ?"],
  [139, "Pourquoi le siphon s’arrête-t-il pendant le soutirage ?"],
  [140, "Quel tire-bouchon choisir pour un bouchon long ou fragile ?"],
  [141, "Pourquoi mon cidre est-il trop gazeux ?"],
  [142, "Pourquoi un bocal ne prend-il pas le vide ?"],
  [143, "Peut-on faire bouillir ou tremper les bouchons avant le bouchage ?"],
  [144, "Comment nettoyer le matériel juste après le soutirage ?"],
  [145, "Combien de sucre ajouter pour la prise de mousse ?"],
  [146, "Peut-on empiler les bocaux dans un stérilisateur ?"],
  [147, "Comment stocker des bouchons neufs avant la mise en bouteille ?"],
  [148, "Peut-on mettre en bouteille directement depuis une dame-jeanne ?"],
  [149, "Quelle bouteille utiliser pour un cidre pétillant ?"],
  [150, "Comment adapter un barème à l’altitude ?"],
  [151, "Combien de temps peut-on conserver un sachet de bouchons entamé ?"],
  [152, "Faut-il un muselet avec un bouchon de cidre ?"],
  [153, "Peut-on stériliser des bocaux au four ?"],
  [154, "Pourquoi un bouchon fuit-il après la mise en bouteille ?"],
  [155, "Combien de temps attendre avant de boire un cidre embouteillé ?"],
  [156, "Comment nettoyer et contrôler un stérilisateur ?"],
  [157, "Pourquoi certains bouchons remontent-ils du goulot ?"],
  [158, "Comment étiqueter et organiser ses conserves ?"],
  [159, "Comment reconnaître un bouchon trop sec ou abîmé ?"],
  [160, "Le diamètre du col de bouteille est-il standard ?"],
  [161, "Peut-on réutiliser un bouchon en liège ?"],
  [162, "Les bouchons agglomérés conviennent-ils au vin ?"],
  [163, "Comment choisir un hachoir ou un presse-tomates ?"],
  [164, "Que faut-il mesurer avant de commander ?"],
  [165, "Quel déshydrateur choisir et comment savoir si un aliment est assez sec ?"],
  [166, "Comment nettoyer le chauffe-cire et la cuve ?"],
  [167, "Comment nettoyer un pressoir après des fruits très colorants ?"],
  [168, "Quand poser l’étiquette : avant ou après le cirage ?"],
  [169, "Comment retirer de la cire sur le verre ou le plan de travail ?"],
  [170, "Comment nettoyer un égouttoir ou un rince-bouteilles ?"],
  [171, "Quel volume de vinaigrier choisir ?"],
  [172, "Quand remplacer un goupillon de bouteille ?"],
  [173, "Peut-on aromatiser le vinaigre dans le vinaigrier ?"],
  [174, "Comment éviter les chocs thermiques sur les bouteilles en verre ?"],
  [175, "Comment conserver le vinaigre une fois soutiré ?"],
  [176, "Comment remplacer une tête ou une pièce d’usure ?"],
  [177, "Pourquoi les bouchons ne sont-ils pas tous enfoncés à la même hauteur ?"],
  [178, "Peut-on stocker du vin dans un garage ?"],
  [179, "Peut-on utiliser une boucheuse à vin pour des bouchons synthétiques ?"],
  [180, "Comment gérer une cave avec des bouteilles de garde différentes ?"],
  [181, "Comment organiser une chaîne de mise en bouteille à deux personnes ?"],
  [182, "Faut-il retourner régulièrement les bouteilles de vin ?"],
  [183, "Quelle marge de perte prévoir lors du soutirage ?"],
  [184, "Comment transporter des bouteilles avant de les servir ?"],
  [185, "Comment échantillonner une bouteille témoin après mise ?"],
  [186, "Pourquoi le cidre devient-il trouble ?"],
  [187, "Faut-il inertiser les bouteilles avant remplissage ?"],
  [188, "Comment obtenir un cidre doux plutôt que brut ?"],
  [189, "Peut-on conserver de l’huile aromatisée en bocal à température ambiante ?"],
  [190, "Peut-on faire du jus de pomme avec le même broyeur et le même pressoir ?"],
  [191, "Peut-on mettre du pâté ou de la viande en conserve à la maison ?"],
  [192, "Comment poser correctement une capsule couronne ?"],
  [193, "Pourquoi la couleur ou la texture change-t-elle au stockage ?"],
  [194, "Peut-on réutiliser un bouchon mécanique de cidre ?"],
  [195, "Que faire si le temps ou la température n’ont pas été respectés ?"],
  [196, "Le bouchon en liège peut-il donner un goût au vin ?"],
  [197, "La cire prolonge-t-elle la durée de garde d’un bouchon en liège ?"],
  [198, "Faut-il adapter le bouchon aux bouteilles anciennes ou récupérées ?"],
  [199, "Un bouchon de catégorie supérieure améliore-t-il un vin simple ?"],
  [200, "Comment calculer le nombre de bouchons à commander ?"],
];

const FAITS_ATTENDUS: Record<number, string[]> = {
  85: ["extracteur-jus.choix"],
  86: ["support-cire.choix"],
  87: ["extracteur-jus.choix"],
  88: ["piece-rechange.procedure"],
  89: ["mere-vinaigre.definition"],
  90: ["ouverture-cire.procedure"],
  91: ["stockage-confiture.condition"],
  92: ["contact-alimentaire.choix"],
  93: ["sechage-bouteilles.procedure"],
  94: ["vin-pour-vinaigre.choix"],
  95: ["support-cire.condition"],
  96: ["stockage-confiture.duree"],
  97: ["compatibilite-produit.choix"],
  98: ["nettoyage-bouteilles.duree"],
  99: ["vinaigre+cidre.condition"],
  100: ["defauts-cire.erreur"],
  101: ["boucheuse.choix"],
  102: ["nettoyage-tuyau.procedure"],
  103: ["casier.choix"],
  104: ["vinaigre.raison"],
  105: ["chauffe-cire.choix"],
  106: ["boucheuse-universelle.definition"],
  107: ["operations-transfert.choix"],
  108: ["nettoyage-col-etroit.procedure"],
  109: ["casier.condition"],
  110: ["mere-vinaigre.raison"],
  111: ["boucheuse.entretien"],
  112: ["mise-en-bouteille.dimension"],
  113: ["eau-javel-bouteilles.condition"],
  114: ["hygrometrie.condition"],
  115: ["pomme.choix"],
  116: ["entretien-robinet-vinaigrier.procedure"],
  117: ["installation-boucheuse.condition"],
  118: ["soutirage.choix"],
  119: ["etiquettes-anciennes.procedure"],
  120: ["hygrometrie.condition"],
  121: ["cidre.moment"],
  122: ["entretien-robinet-vinaigrier.procedure"],
  123: ["bouchage+format-bouteille-boucheuse.condition"],
  124: ["arret-remplissage.procedure"],
  125: ["hygrometrie.condition"],
  126: ["pomme.duree"],
  127: ["remplissage-bocal.choix"],
  128: ["securite-bouchage.condition"],
  129: ["bouteille-humide.condition"],
  130: ["carafage-vin.moment"],
  131: ["nettoyage-materiel-cidre.procedure"],
  132: ["remplissage-bocal.dimension"],
  133: ["boucheuse.dimension"],
  134: ["pertes-soutirage.procedure"],
  135: ["service-vieux-vin.procedure"],
  136: ["cidre.erreur"],
  137: ["incident-traitement-conserve.raison"],
  138: ["preparation-bouchon.choix"],
  139: ["soutirage.erreur"],
  140: ["choix-tire-bouchon-fragile.choix"],
  141: ["sucre-cidre.raison"],
  142: ["incident-traitement-conserve.raison"],
  143: ["bouchon-liege.condition"],
  144: ["nettoyage-tuyau.procedure"],
  145: ["sucre-cidre.dimension"],
  146: ["empilage-bocaux.condition"],
  147: ["stockage-bouchons.procedure"],
  148: ["mise-en-bouteille.condition"],
  149: ["bouteille+cidre.choix"],
  150: ["bareme-conserve.procedure"],
  151: ["bouchon-liege.duree"],
  152: ["bouchage+cidre.choix"],
  153: ["conserve-au-four.condition"],
  154: ["repos-bouchage.raison"],
  155: ["maturation-cidre.duree"],
  156: ["sterilisateur.procedure"],
  157: ["repos-bouchage.raison"],
  158: ["etiquetage-conserves.procedure"],
  159: ["etat-bouchon.choix"],
  160: ["taille-bouchon.dimension"],
  161: ["reemploi-bouchon.condition"],
  162: ["bouchon-agglomere.condition"],
  163: ["presse-tomates.choix"],
  164: ["mesures-commande.procedure"],
  165: ["deshydrateur.choix"],
  166: ["nettoyage-chauffe-cire.procedure"],
  167: ["nettoyage-bouteilles+nettoyage-materiel-cidre.procedure"],
  168: ["ordre-etiquette-cire.moment"],
  169: ["nettoyage-cire.procedure"],
  170: ["egouttoir+rince-bouteille.choix"],
  171: ["vinaigrier.choix"],
  172: ["goupillon-usure.moment"],
  173: ["aromatisation-vinaigre.condition"],
  174: ["bouteille.condition"],
  175: ["stockage-vinaigre.entretien"],
  176: ["piece-rechange.procedure"],
  177: ["controle-bouchage.erreur"],
  178: ["garage-vin.condition"],
  179: ["boucheuse+bouchon-synthetique.condition"],
  180: ["cave.procedure"],
  181: ["organisation-mise.procedure"],
  182: ["rotation-bouteilles.condition"],
  183: ["pertes-soutirage.dimension"],
  184: ["transport-bouteilles.procedure"],
  185: ["bouteille-temoin.procedure"],
  186: ["cidre-trouble.raison"],
  187: ["inertage-bouteilles.condition"],
  188: ["style-cidre.choix"],
  189: ["huile-aromatisee.condition"],
  190: ["jus.usage"],
  191: ["viande-en-conserve.condition"],
  192: ["capsuleuse.procedure"],
  193: ["alteration-conserve.raison"],
  194: ["bouchon-mecanique-cidre.condition"],
  195: ["incident-traitement-conserve.condition"],
  196: ["gout-bouchon.condition"],
  197: ["cire+bouchon-liege.duree"],
  198: ["taille-bouchon.choix"],
  199: ["categorie-bouchon.condition"],
  200: ["quantite-commande.procedure"],
};

describe("les questions prioritaires P2 et P3", () => {
  it("contient exactement et dans l’ordre les 116 priorités restantes", () => {
    expect(QUESTIONS).toHaveLength(116);
    expect(QUESTIONS.map(([rang]) => rang)).toEqual(Array.from({ length: 116 }, (_, index) => index + 85));
    expect(Object.keys(FAITS_ATTENDUS).map(Number)).toEqual(Array.from({ length: 116 }, (_, index) => index + 85));
  });

  it.each(QUESTIONS)("priorité n°%i — %s", (rang, question) => {
    const trace = assistant.repondre(question).trace;
    const faitsAcceptables = FAITS_ATTENDUS[rang]!;
    expect(
      trace.faits.some((fait) => faitsAcceptables.includes(fait)),
      `${question} → type=${trace.type ?? "aucun"}; concepts=${trace.concepts.join(", ") || "aucun"}; faits=${trace.faits.join(", ") || "aucun"}`,
    ).toBe(true);
  });
});
